# Default values for jk8-jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
imagePullSecrets: ["artifactory-registry-key"]
nameOverride: ""
fullnameOverride: ""
dockerRegistry: docker-registry.example.com

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

ingress:
  fqdn: jenkins-master.example.com

artifactory:
  dockerconfigjson: |
    {
      "auths":{
      "docker-registry.example.com":{
        "username":"registryuser",
        "password":"password",
        "auth": "cmVnaXN0cnl1c2VyOnBhc3N3b3Jk"
        }
      }
    }

resources:
  limits:
    memory: "4Gi"
    cpu: "4"
  requests:
    memory: "4Gi"
    cpu: "4"
