apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jk8-jenkins.fullname" . }}-jenkins-admin-credentials
type: Opaque
data:
  JENKINS_USER: YWRtaW4=         # Base64-encoded value of "admin"
  JENKINS_PASSWORD: YWRtaW4xMjM=  # Base64-encoded value of "admin123"