apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "jk8-jenkins.fullname" . }}-egress
spec:
  egress:
    - toEndpoints:
        - matchLabels:
            app: external-service
    - toEntities:
        - world
    - toServices:
        - namespace: default
          name: my-service
  endpointSelector:
    matchLabels:
      {{- include "jk8-jenkins.selectorLabels" . | nindent 6 }}