apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hool-jenkins.fullname" . }}
  labels:
    {{- include "hool-jenkins.labels" . | nindent 4 }}
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
