apiVersion: v1
kind: Service
metadata:
  name: {{ include "hool-jenkins.fullname" . }}
  labels:
    {{- include "hool-jenkins.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: tcp-50000
      port: 50000
      targetPort: 50000
      protocol: TCP
  selector:
    {{- include "hool-jenkins.selectorLabels" . | nindent 4 }}