apiVersion: v1
kind: Service
metadata:
  name: {{ include "hool-jenkins.fullname" . }}-tcp
  labels:
    {{- include "hool-jenkins.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-jnlp
      port: 50000
      targetPort: 50000
      protocol: TCP
  selector:
    {{- include "hool-jenkins.selectorLabels" . | nindent 4 }}