apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: "{{ include "jk8-jenkins.fullname" . }}-tcp-proxy"
  labels:
    {{- include "jk8-jenkins.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: contour-corp
spec:
  tcpproxy:
    services:
    - name: {{ include "jk8-jenkins.fullname" . }}-tcp
      port: 50000